# Generated by Django 4.2 on 2023-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_image_customer_debt_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='remaining_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
