# Generated by Django 4.2 on 2023-08-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
