# Generated by Django 4.2 on 2023-04-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_products', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Mattress',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='mattresses',
            field=models.ManyToManyField(related_name='ordered_products', to='purchase.perproduct'),
        ),
    ]
