# Generated by Django 4.2 on 2023-04-21 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_perproduct_delete_mattress_delete_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='ordered_products',
        ),
    ]
