# Generated by Django 4.2 on 2023-08-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
    ]
