# Generated by Django 4.2 on 2023-08-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_accessory_covermaterial_rawmaterialcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterialcategory'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='inventory.supplier'),
        ),
    ]
