# Generated by Django 4.2 on 2023-09-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_covermaterialtransaction_accessorytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessorytransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='covermaterialtransaction',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='rawmaterialtransaction',
            name='transaction_date',
        ),
    ]
