# Generated by Django 4.2 on 2023-08-20 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wallet.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reference', models.CharField(default=wallet.utils.generate_reference, max_length=15, unique=True)),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('success', 'success'), ('error', 'error'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('payment', 'payment'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer')], max_length=100)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.userwallet')),
            ],
        ),
        migrations.CreateModel(
            name='MonnifyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monnify_account_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('account_reference', models.CharField(help_text='Your unique reference used to identify this reserved account', max_length=255)),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('currency_code', models.CharField(default='NGN', max_length=255)),
                ('bvn', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monnify', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitiatedMonnifyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('payment_reference', models.CharField(max_length=255)),
                ('payment_status', models.CharField(default='UNPAID', max_length=255)),
                ('oder_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_monnify_transaction', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
